FROM eclipse-temurin:21-jre

WORKDIR /opt/keycloak/providers/

COPY target/keycloak-kafka-listener-0.0.1-SNAPSHOT-jar-with-dependencies.jar \
     /opt/keycloak/providers/keycloak-kafka-listener.jar

